# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12

    # Setting up environment
    - name: Install yarn
      run: npm install -g yarn
    
    - name: Install project dependencies
      run: yarn install
      
    - name: Making Production Build
      run: CI=false yarn build
    
    - name: Install Surge
      run: npm install -g surge
    
    - name: Deploy on Surge
      run: surge ./build/ shoestorebc2020-waqas.surge.sh --token ${{ secrets.SURGE_TOKEN }}
